# Generated by Django 5.0.4 on 2024-09-14 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_empresa_created_at_empresa_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
            preserve_default=False,
        ),
    ]
