# Generated by Django 5.0.4 on 2024-09-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_avaliacao_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
