# Generated by Django 5.0.4 on 2024-09-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_alter_avaliacao_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='empresa',
        ),
    ]
